mom_host: rabbitmq

inputs:
  - type: queue
    name: transactions_queue

outputs:
  - type: queue
    name: q3_queue

strategy:
  type: currency
  params:
    target_currency: "US Dollar"
    output_queue: q3_queue
