mom_host: rabbitmq

# You can keep input_queue, or use the new 'inputs' list format
inputs:
  - name: transactions_queue

# The new outputs list format required by your parser
outputs:
  - type: queue
    name: q4_queue

log_level: DEBUG

strategy:
  type: currency
  params:
    target_currency: "US Dollar"