mom_host: rabbitmq

input_queue: q4_queue
output_queue: result_queue

strategy:
  type: amount_less_than
  params:
    threshold: 5
    output_queue: result_queue
    field_name: count

projection:
  fields:
    - from_account
    - to_account
    - amount_paid
