mom_host: rabbitmq

input_exchange: q4_scatter_route_exchange

input_queue: q4_scatter_route_0

output_queue: q4_scatter_filter_queue

base_routing_key: q4_scatter_route

log_level: DEBUG

strategy:
  type: ScatterAggregator