services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_QUEUE=transactions_queue
    - ACCOUNTS_QUEUE=accounts_queue
    - INPUT_QUEUE=result_queue
    - SERVER_PORT=5678

  filter_usd_0:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filter_usd_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_config.yaml:/app/config.yaml:ro
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=transactions_queue
    - OUTPUT_QUEUE=q2_queue

  q2_group_max_amount_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q2_group_max_amount_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=q2_queue
    - OUTPUT_EXCHANGE=q2_group_output_exchange
    - STRATEGY=BankMaxAmount
    - BASE_ROUTING_KEY=q2_aggregator_input
    - TOTAL_AGGREGATORS=1
    - EOF_FANOUT=q2_group_max_amount_eof
    - EXPECTED_EOFS=1

  q2_aggregator_max_amount_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q2_aggregator_max_amount_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/max_amount_per_bank_config.yaml:/app/config.yaml:ro
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE=q2_group_output_exchange
    - INPUT_QUEUE=q2_aggregator_input
    - OUTPUT_QUEUE=q2_aggregator_output_queue
    - STRATEGY=BankMaxAmount
    - EOF_FANOUT=q2_aggregator_max_amount_eof
    - EXPECTED_EOFS=1

  q2_join_bank_max_amount_0:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q2_join_bank_max_amount_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q2_bank_max_amount_config.yaml:/app/config.yaml:ro
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=q2_aggregator_output_queue
    - ACCOUNTS_INPUT_QUEUE=accounts_queue
    - OUTPUT_QUEUE=result_queue
    - STRATEGY=BankMaxAmount
    - EOF_FANOUT=q2_join_bank_max_amount_eof
    - EXPECTED_EOFS=1

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    depends_on:
    - gateway
    volumes:
    - ./data/sample.csv:/data/transactions.csv:ro
    - ./data/accounts_sample.csv:/data/accounts.csv:ro
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - TRANSACTIONS_DATASET_PATH=/data/transactions.csv
    - ACCOUNTS_DATASET_PATH=/data/accounts.csv
    - BATCH_SIZE=${BATCH_SIZE:-500}

  client_1:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    depends_on:
    - gateway
    volumes:
    - ./data/sample.csv:/data/transactions.csv:ro
    - ./data/accounts_sample.csv:/data/accounts.csv:ro
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - TRANSACTIONS_DATASET_PATH=/data/transactions.csv
    - ACCOUNTS_DATASET_PATH=/data/accounts.csv
    - BATCH_SIZE=${BATCH_SIZE:-500}
