services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_USD_EXCHANGE=transactions_usd_exchange
    - TRANSACTIONS_DATE_EXCHANGE=transactions_date_exchange
    - ACCOUNTS_EXCHANGE=merge_max_by_account_exchange
    - RESULT_EXCHANGE=gateway_results_exchange
    - SERVER_PORT=5678
    - TRANSACTIONS_USD_WORKERS=2
    - TRANSACTIONS_DATE_WORKERS=2
    - ACCOUNTS_WORKERS=1
    - EXPECTED_RESULTS=4

  filtro_usd_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filtro_usd_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_fanout_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=2

  filtro_usd_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filtro_usd_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_fanout_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=2

  q1_filter_lt50_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1

  q1_filter_lt50_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1

  q1_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q1_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q1_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=1

  q2_group_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q2_group_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q2_bank_max_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded

  q2_group_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q2_group_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q2_bank_max_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded

  q2_aggregator_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q2_aggregator_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/max_amount_per_bank_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin

  q2_aggregator_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q2_aggregator_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/max_amount_per_bank_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin

  q2_merge:
    build:
      context: .
      dockerfile: src/merge/Dockerfile
    container_name: q2_merge
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/merge/config/accounts_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1

  q2_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q2_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q2_result.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=2

  q3_router_1:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q3_router_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q3_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2

  q3_router_2:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q3_router_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q3_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2

  q3_group_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q3_group_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded

  q3_group_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q3_group_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded

  q3_aggregator_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q3_aggregator_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin

  q3_aggregator_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q3_aggregator_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin

  q3_averages_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q3_averages_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q3_averages_broadcast_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=broadcast

  q3_historical_filter_1:
    build:
      context: .
      dockerfile: src/historical_filter/Dockerfile
    container_name: q3_historical_filter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/historical_filter/config/q3.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1

  q3_historical_filter_2:
    build:
      context: .
      dockerfile: src/historical_filter/Dockerfile
    container_name: q3_historical_filter_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/historical_filter/config/q3.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1

  q3_result_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q3_result_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q3_result_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=3

  q5_router_1:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q5_router_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q5_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1

  q5_router_2:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q5_router_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q5_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=1

  q5_converter_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q5_converter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/currency_conversion_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1

  q5_converter_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q5_converter_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/currency_conversion_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1

  q5_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q5_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q5_join_count_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=5

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 15 && python -m src.client.main"]
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/small_trans.csv:/data/small_trans.csv
    - ./data/small_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_0:/results/clients/client_0
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_0/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500
