services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_USD_EXCHANGE=transactions_usd_exchange      # -> Filtro USD
    - TRANSACTIONS_DATE_EXCHANGE=transactions_date_exchange    # -> router Q5 (todas las monedas)
    - ACCOUNTS_EXCHANGE=merge_max_by_account_exchange          # -> merge de Q2
    - RESULT_EXCHANGE=gateway_results_exchange
    - SERVER_PORT=5678
    - TRANSACTIONS_USD_WORKERS=1
    - TRANSACTIONS_DATE_WORKERS=1
    - ACCOUNTS_WORKERS=1
    - EXPECTED_RESULTS=5    # Q1+Q2+Q3+Q4+Q5;

  filtro_usd_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filtro_usd_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_fanout_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=filtro_usd

  filtro_usd_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filtro_usd_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_fanout_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=filtro_usd

  q1_filter_lt50_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q1_filter_lt50

  q1_filter_lt50_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q1_filter_lt50

  q1_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q1_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q1_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=1
    - STAGE_NAME=q1_join

  q2_group_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q2_group_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q2_bank_max_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=q2_group_bank_max

  q2_group_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q2_group_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q2_bank_max_input_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=q2_group_bank_max

  q2_aggregator_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q2_aggregator_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/max_amount_per_bank_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin
    - STAGE_NAME=q2_aggregator

  q2_aggregator_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q2_aggregator_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/max_amount_per_bank_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin
    - STAGE_NAME=q2_aggregator

  q2_merge:
    build:
      context: .
      dockerfile: src/merge/Dockerfile
    container_name: q2_merge
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/merge/config/accounts_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q2_merge

  q2_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q2_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q2_result.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=2
    - STAGE_NAME=q2_join

  q3_q4_router_1:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q3_q4_router_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q3_q4_dates.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=2        # filtro_usd
    - WORKER_ID=1
    - STAGE_NAME=q3_q4_router

  q3_q4_router_2:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q3_q4_router_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q3_q4_dates.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=2        # filtro_usd
    - WORKER_ID=2
    - STAGE_NAME=q3_q4_router

  q3_group_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q3_group_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=q3_group

  q3_group_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q3_group_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=q3_group

  q3_aggregator_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q3_aggregator_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin
    - STAGE_NAME=q3_aggregator

  q3_aggregator_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q3_aggregator_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q3_payment_avg.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=round_robin
    - STAGE_NAME=q3_aggregator

  q3_averages_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q3_averages_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q3_averages_broadcast_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=broadcast
    - STAGE_NAME=q3_averages_join

  q3_historical_filter_1:
    build:
      context: .
      dockerfile: src/historical_filter/Dockerfile
    container_name: q3_historical_filter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/historical_filter/config/q3.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q3_historical_filter

  q3_historical_filter_2:
    build:
      context: .
      dockerfile: src/historical_filter/Dockerfile
    container_name: q3_historical_filter_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/historical_filter/config/q3.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=3
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q3_historical_filter

  q3_result_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q3_result_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q3_result_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=3
    - STAGE_NAME=q3_result_join

  group_scatter_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_scatter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q4_scatter_group.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=group_scatter

  group_scatter_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_scatter_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q4_scatter_group.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=group_scatter

  aggregator_scatter_group_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_scatter_group_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_scatter_aggregator.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=scatter_aggregator

  aggregator_scatter_group_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_scatter_group_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_scatter_aggregator.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=scatter_aggregator

  merge_with_self_1:
    build:
      context: .
      dockerfile: src/merge/Dockerfile
    container_name: merge_with_self_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/merge/config/selfmerge.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=self_merge

  merge_with_self_2:
    build:
      context: .
      dockerfile: src/merge/Dockerfile
    container_name: merge_with_self_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/merge/config/selfmerge.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=self_merge

  group_account_pair_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_account_pair_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/account_pair_count.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=group_account_pair
    
  aggreator_account_pair_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_account_pair_0 
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/account_pairs_aggregator.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=aggregator_account_pair

  group_account_pair_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_account_pair_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/account_pair_count.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=group_account_pair

  group_by_accounts_1:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_by_accounts_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/group_by_accounts.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=group_accounts

  group_by_accounts_2:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_by_accounts_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/group_by_accounts.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=2
    - ROUTING_STRATEGY=sharded
    - STAGE_NAME=group_accounts

  aggregator_accounts_1:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_accounts_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_aggregator_accounts.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=aggregator_accounts

  aggregator_accounts_2:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_accounts_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_aggregator_accounts.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=aggregator_accounts

  q4_join_0:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q4_join_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q4_result.yaml:/app/config.yaml:ro
    - ./persisted_state:/app/state
    environment:
    - EOF_EXPECTED=2
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=4
    - STAGE_NAME=join_query_result

  q5_router_1:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q5_router_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q5_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=1
    - STAGE_NAME=q5_router

  q5_router_2:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: q5_router_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q5_dates_scaled.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=1
    - STAGE_NAME=q5_router

  q5_converter_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q5_converter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/currency_conversion_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q5_converter

  q5_converter_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q5_converter_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/currency_conversion_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q5_converter

  q5_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q5_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q5_join_count_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=5
    - STAGE_NAME=q5_join

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 15 && python -m src.client.main"]
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/LI-Medium_Trans.csv:/data/small_trans.csv
    - ./data/LI-Medium_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_0:/results/clients/client_0
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_0/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500

  client_1:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 15 && python -m src.client.main"]
    container_name: client_1
    depends_on:
    - gateway
    volumes:
    - ./data/LI-Medium_Trans.csv:/data/small_trans.csv
    - ./data/LI-Medium_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_1:/results/clients/client_1
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_1/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500

  client_2:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 15 && python -m src.client.main"]
    container_name: client_2
    depends_on:
    - gateway
    volumes:
    - ./data/LI-Medium_Trans.csv:/data/small_trans.csv
    - ./data/LI-Medium_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_2:/results/clients/client_2
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_2/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500
