mom_host: rabbitmq

input_queue: "queue_9/1-9/5_shard_2"
output_exchange: q3_aggregate_exchange
eof_fanout: q3_group_eof_2
expected_eofs: 1

strategy:
  type: PaymentFormatAverage
  params:
    base_routing_key: aggregate_route
    shard_amount: 3
