services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_USD_EXCHANGE=transactions_exchange
    - TRANSACTIONS_DATE_EXCHANGE=transactions_unused_exchange
    - ACCOUNTS_QUEUE=accounts_queue
    - RESULT_EXCHANGE=gateway_results_exchange
    - SERVER_PORT=5678

  transaction_router_0:
    build:
      context: .
      dockerfile: src/transaction_router/Dockerfile
    container_name: transaction_router_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/transaction_router/config/q1_only.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1

  q1_filter_less_than_fifty_0:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_less_than_fifty_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_with_router_config.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1

  q1_join_0:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q1_join_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q1_config.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=1

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 10 && python -m src.client.main"]
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/small_trans.csv:/data/small_trans.csv
    - ./data/small_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_0:/results/clients/client_0
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_0/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500
