services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672


  # ----- Gateway (Trx Fan Out): publica a la rama USD y a la rama date (Q5) -----

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_USD_EXCHANGE=transactions_usd_exchange      # -> Filtro USD
    - TRANSACTIONS_DATE_EXCHANGE=transactions_date_exchange    # -> router Q5 (todas las monedas)
    - ACCOUNTS_EXCHANGE=merge_max_by_account_exchange          # -> merge de Q2
    - RESULT_EXCHANGE=gateway_results_exchange
    - SERVER_PORT=5678
    - TRANSACTIONS_USD_WORKERS=1
    - TRANSACTIONS_DATE_WORKERS=1
    - ACCOUNTS_WORKERS=1
    - EXPECTED_RESULTS=1    # Q1+Q2+Q3+Q4+Q5;


  filtro_usd:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filtro_usd
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_fanout_config.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1        # gateway
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=2
    - STAGE_NAME=filtro_usd

  # ===================== Q1 =====================

  q1_filter_lt50_1:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q1_filter_lt50
    - FD_ENABLED=1
    - FD_NODES=1:q1_filter_lt50_1,2:q1_filter_lt50_2

  q1_filter_lt50_2:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q1_filter_lt50_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/q1_lt50_input_config.yaml:/app/config.yaml:ro
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - WORKER_ID=2
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - STAGE_NAME=q1_filter_lt50
    - FD_ENABLED=1
    - FD_NODES=1:q1_filter_lt50_1,2:q1_filter_lt50_2

  q1_join:
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q1_join
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q1_config.yaml:/app/config.yaml:ro
    environment:
    - WORKER_ID=1
    - EOF_EXPECTED=2
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=1
    - STAGE_NAME=q1_join


  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 10 && python -m src.client.main"]
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/small_trans.csv:/data/small_trans.csv
    - ./data/small_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_0:/results/clients/client_0
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_0/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500
