services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_EXCHANGE=transactions_exchange
    - ACCOUNTS_QUEUE=accounts_queue
    - RESULT_EXCHANGE=gateway_results_exchange
    - SERVER_PORT=5678

  filter_usd_0:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: filter_usd_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_config.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1

  # filter_by_datetime_0:
  #   build:
  #     context: .
  #     dockerfile: src/filter/Dockerfile
  #   container_name: filter_by_datetime_0
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   volumes:
  #   - ./src/filter/config/datetime_config.yaml:/app/config.yaml:ro
  #   environment:
  #   - EOF_EXPECTED=1
  #   - WORKER_ID=1
  #   - NUM_DOWNSTREAM_WORKERS=1

  group_scatter_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_scatter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q4_scatter_group.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=sharded

  aggregator_scatter_group_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_scatter_group_0 
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_scatter_aggregator.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=sharded

  merge_with_self_0:
    build:
      context: .
      dockerfile: src/merge/Dockerfile
    container_name: merge_with_self_0 
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/merge/config/selfmerge.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1

  group_account_pair_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_account_pair_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/account_pair_count.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    
  aggreator_account_pair_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_account_pair_0 
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/account_pairs_aggregator.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1

  group_by_accounts_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: group_by_accounts_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/group_by_accounts.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - ROUTING_STRATEGY=sharded

  aggregator_accounts_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: aggregator_accounts_0 
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_aggregator_accounts.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1

  q4_join_0:  
    build:
      context: .
      dockerfile: src/join/Dockerfile
    container_name: q4_join_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/join/config/q4_result.yaml:/app/config.yaml:ro
    environment:
    - EOF_EXPECTED=1
    - WORKER_ID=1
    - NUM_DOWNSTREAM_WORKERS=1
    - QUERY_RESULT_NUMBER=4

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command: ["sh", "-c", "sleep 10 && python -m src.client.main"]
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/small_trans.csv:/data/small_trans.csv
    - ./data/small_accounts.csv:/data/small_accounts.csv
    - ./results/clients/client_0:/results/clients/client_0
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - OUTPUT_PATH=/results/clients/client_0/
    - ACCOUNTS_PATH=/data/small_accounts.csv
    - TRANSACTIONS_PATH=/data/small_trans.csv
    - BATCH_SIZE=500
