services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    - MOM_HOST=rabbitmq
    - TRANSACTIONS_QUEUE=transactions_queue
    - INPUT_QUEUE=result_queue
    - SERVER_PORT=5678

  q4_filter_usd_0:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q4_filter_usd_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/usd_config.yaml:/app/config.yaml:ro

  q4_filter_by_datetime_0:
    build:
      context: .
      dockerfile: src/filter/Dockerfile
    container_name: q4_filter_by_datetime_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/filter/config/date_multiplex_config.yaml:/app/config.yaml:ro

  q4_selfmerge_route_group_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q4_selfmerge_route_group_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q4_selfmerge_route.yaml:/app/config.yaml:ro

  q4_merge_with_self_0:
    build:
      context: .
      dockerfile: src/joiner/Dockerfile
    container_name: q4_merge_with_self_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/joiner/config/q4_merge_with_self.yaml:/app/config.yaml:ro
    environment:
    - SHARD_ID=0

  q4_group_by_orig_dest_0:
    build:
      context: .
      dockerfile: src/group/Dockerfile
    container_name: q4_group_by_orig_dest
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/group/config/q4_group_by_orig_dest.yaml:/app/config.yaml:ro

  q4_aggregator_count_pairs_0:
    build:
      context: .
      dockerfile: src/aggregator/Dockerfile
    container_name: q4_aggregator_count_pairs_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./src/aggregator/config/q4_aggregator_count_pairs.yaml:/app/config.yaml:ro
    environment:
    - SHARD_ID=0

  client_0:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: client_0
    depends_on:
    - gateway
    volumes:
    - ./data/LI-Small_Trans.csv:/data/dataset.csv:ro
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - DATASET_PATH=/data/dataset.csv
    - BATCH_SIZE=500
